version: '3'
services:
  catalog-admin-service:
    image: eu.gcr.io/digdir-fdk-infra/catalog-admin-service:test
    build: .
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27017:27017'
