logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB:catalog_admin}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: ${KEYCLOAK_OIDC_ISSUER:https://auth.staging.fellesdatakatalog.digdir.no/realms/fdk}/protocol/openid-connect/certs
    issuer-uri: ${KEYCLOAK_OIDC_ISSUER:https://auth.staging.fellesdatakatalog.digdir.no/realms/fdk}
application:
  adminServiceUri: ${CATALOG_ADMIN_SERVICE_URI:https://catalog-admin-service.staging.fellesdatakatalog.digdir.no}
  cors.originPatterns: "${CORS_ORIGIN_PATTERNS}"
---
spring:
  config.activate.on-profile: develop
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_admin
    username: admin
    password: admin
server:
  port: 8080
application.cors.originPatterns: "*"
---
spring:
  config.activate.on-profile: integration-test
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: http://localhost:5050/auth/realms/fdk/protocol/openid-connect/certs
    issuer-uri: http://localhost:5050/auth/realms/fdk
application.cors.originPatterns: "*"
